# Generated by Django 5.2 on 2025-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="ORD", max_length=15),
            preserve_default=False,
        ),
    ]
