# Generated by Django 5.2 on 2025-06-16 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=12,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="WRONG_PHONE_NUMBER",
                                message="Phone number must begin with 998 and contain only 12 numbers",
                                regex="^998\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("default_shipping_address", models.TextField()),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
